version: "3.0"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    hostname: elastic-search-server
    container_name: elastic-search-server
    restart: unless-stopped
    environment:
      - cluster.name=elasticsearch-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${DOCKER_PATH}/ElasticSearch/ElasticSearchData:/usr/share/elasticsearch/data
      - ${DOCKER_PATH}/ElasticSearch/ElasticSearchConfig:/usr/share/elasticsearch/config
    ports:
      - "9200:9200"
    networks:
      - elasticsearch-net
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS:http://elasticsearch:9200
    volumes:
      - ${DOCKER_PATH}/ElasticSearch/KibanaConfig:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elasticsearch-net
    depends_on:
      - elasticsearch

networks:
  elasticsearch-net:
    driver: bridge