version: "3.0"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - cluster.name=elasticsearch-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-config:/usr/share/elasticsearch/config
    ports:
      - "9200:9200"
    networks:
      - elasticsearch-net
      
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS:http://elasticsearch:9200
    volumes:
      - kibana-config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elasticsearch-net
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
    driver: local

  elasticsearch-config:
    driver: local
  
  kibana-config:
    driver: local

networks:
  elasticsearch-net: